# Site settings
title: a Vert.x community in China | 一个中国Vert.x社区
email: vertxer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vertxer.org is a Vert.x user community in China, sharing Vert.x best practice, discuss architecture problem, contribute vert.x module, launch regular meetup in Beijing ,and spread Vert.x. | Vertxer.org是一个Vert.x中国用户社区，致力于分享Vert.x技术问题。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vertxer.org" # the base hostname & protocol for your site
twitter_username: vertxer
github_username:  vertxer

# Build settings
markdown: kramdown
